### ISSUE TITLE
Make the jwt.secret private

### ISSUE THREAD

**Issue by plindnercs** [GreenPassApp/greenpass-backend#1]
I'm by no means a security expert, but I think the HMAC secret should not be available to the public.

Maybe you could change it to something more complex and add it to some kind of external configuration, so that it isn't visible on the public github project.

**Comment by JakobStadlhuber** [comment]
Do you mean the [jwt.secret  property](https://github.com/GreenPassApp/greenpass-backend/blob/3e7e1e44dfc4af8b287b02d0d15ca3c25122822b/src/main/resources/application.properties#L21) ?
No worries like the presskit properties, this information will be overridden at runtime. Does this answer your concerns?

**Comment by JakobStadlhuber** [comment]
But it's probably a good idea to document this, thanks.

**Comment by plindnercs** [comment]
Yeah that answers my question, was just a bit confused while browsing through the code.
Thanks!
